### ISSUE TITLE
支持支付宝小程序吗

### ISSUE THREAD

**Issue by LaoZhangAndroid** [catsayer-heat/lyc-taro3-f2#1]

**Comment by catsayer-heat** [comment]
我刚才去试了一下，发现支付宝是不支持的（抱歉 我以为他们api基本是一样的，没想到偏偏缺少了那个），我刚才尝试去支持了一下，虽然可以写，但是貌似无法高清设置。目前我还没想到如何去解决，因为在我看来是略微有一丁丁点儿模糊的（在开发者工具中），有点强迫症，所以暂时还没有去支持支付宝小程序

**Comment by LaoZhangAndroid** [comment]
高清设置可以参考 my-f2 相信大佬可以弄出来的

**Comment by catsayer-heat** [comment]
> 高清设置可以参考 my-f2 相信大佬可以弄出来的
今天有点时间就写了一下，目前是支持支付宝小程序了，但是还没有支持支付宝小程序高清设置，我参考了大佬的my-f2，但是依然没有成功，原因是：在我this.setState  设置canvas width height 属性后，antv/f2 中dpr设置失效了，不知道是不是我写错了，有空的时候再看一下吧。
