### ISSUE TITLE
请问有VUE版本吗？

### ISSUE THREAD

**Issue by luoaz123** [catsayer-heat/lyc-taro3-f2#2]
本人小白，不知道如何在taro3.x上面集成VUE版本的f2，如果大佬有方案的话烦请指教下呢，  我试了F2官方的wx-f2、taro-f2都不行，求指教！！！

**Comment by catsayer-heat** [comment]
- 抱歉，当前只对React版本进行了支持，并不支持Vue版本。
- taro-f2是对taro2.x版本的支持，由于taro3引入wx核心库的方式改变了，所以并不支持taro3.x。
- 而wx-f2，是对原生小程序的支持，你可以尝试使用taro3使用原生模块的方式进行引入，你说你尝试使用wx-f2是不行的，我不知道你引入的方式是否正确，按理来说应该是可以的，这里附上taro引入原生模块的文档给你参考：[文档](https://taro-docs.jd.com/taro/docs/hybrid#%E4%BD%BF%E7%94%A8%E5%8E%9F%E7%94%9F%E7%BB%84%E4%BB%B6)
