### ISSUE TITLE
当设置背景色时，在ios上正常，在部分安卓手机上【荣耀v30】显示成黑白

### ISSUE THREAD

**Issue by LiYZHe** [catsayer-heat/lyc-taro3-f2#6]
chart.guide().rect({
        start: ['min', 'min'],
        end: [`max`, 'max'],
        style: {
          fill: '#FF738E',
          fillOpacity: 0.05
        }
      });

**Comment by LiYZHe** [comment]
![WHo FR 1 6 75](https://user-images.githubusercontent.com/43265764/129994704-4b2f23c8-12e8-4204-bd7f-8a580409a74f.png)

**Comment by catsayer-heat** [comment]
这个组件相当于给antv-f2做了一层代理，让其可以在小程序上使用，类似于接口的代理转发。里面的具体功能并非我这里实现。另外，你要看对应的小程序的版本

**Comment by LiYZHe** [comment]
好的，谢谢，实现原理跟wx-f2类似
