### ISSUE TITLE
微信小程序运行报错

### ISSUE THREAD

**Issue by ciwind** [catsayer-heat/lyc-taro3-f2#8]
<img width="719" alt="image" src="https://user-images.githubusercontent.com/5284811/167438811-eab52380-3fc4-4db6-9ba2-285e2216aa19.png">
编译微信小程序，执行报错：Cannot read property 'theme' of undefined，然后白屏。请问是需要做什么配置吗？

**Comment by catsayer-heat** [comment]
...你好，你这样我只知道缺少属性theme，其它都不知道，也不知道你代码怎么写的，或者你把例子改一下弄到你的项目试一下，或者你能提供给我一个完整的事例

**Comment by ciwind** [comment]
我知道了，@antv/f2的版本改成3.8.1的就好了，原来装的是4
